namespace: petclinic-staging

services:
  config-server:
    enabled: true
    image: springcommunity/spring-petclinic-config-server:latest
    containerPort: 8888
    port: 8888
    serviceType: ClusterIP

  discovery-server:
    enabled: true
    image: springcommunity/spring-petclinic-discovery-server:latest
    containerPort: 8761
    port: 8761
    serviceType: ClusterIP
    useEureka: true

  customers-service:
    enabled: true
    image: springcommunity/spring-petclinic-customers-service:latest
    containerPort: 8081
    port: 8081
    serviceType: ClusterIP
    useEureka: true

  visits-service:
    enabled: true
    image: springcommunity/spring-petclinic-visits-service:latest
    containerPort: 8082
    port: 8082
    serviceType: ClusterIP
    useEureka: true

  vets-service:
    enabled: true
    image: springcommunity/spring-petclinic-vets-service:latest
    containerPort: 8083
    port: 8083
    serviceType: ClusterIP
    useEureka: true

  api-gateway:
    enabled: true
    image: springcommunity/spring-petclinic-api-gateway:latest
    containerPort: 8080
    port: 8080
    serviceType: ClusterIP
    useEureka: true

  admin-server:
    enabled: true
    image: springcommunity/spring-petclinic-admin-server:latest
    containerPort: 9090
    port: 9090
    serviceType: ClusterIP

  tracing-server:
    enabled: true
    image: openzipkin/zipkin:latest
    containerPort: 9411
    port: 9411
    serviceType: ClusterIP

# Monitoring configuration
prometheus:
  enabled: true
  server:
    service:
      type: LoadBalancer
  alertmanager:
    enabled: true
    service:
      type: ClusterIP
  serverFiles:
    prometheus.yml:
      rule_files:
        - "alert_rules.yml"
      scrape_configs:
        - job_name: prometheus
          static_configs:
            - targets: ['localhost:9090']
        - job_name: api-gateway
          metrics_path: /actuator/prometheus
          static_configs:
            - targets: ['api-gateway.petclinic-staging.svc.cluster.local:8080']
        - job_name: customers-service
          metrics_path: /actuator/prometheus
          static_configs:
            - targets: ['customers-service.petclinic-staging.svc.cluster.local:8081']
        - job_name: visits-service
          metrics_path: /actuator/prometheus
          static_configs:
            - targets: ['visits-service.petclinic-staging.svc.cluster.local:8082']
        - job_name: vets-service
          metrics_path: /actuator/prometheus
          static_configs:
            - targets: ['vets-service.petclinic-staging.svc.cluster.local:8083']
    alert_rules.yml:
      groups:
        - name: petclinic-staging-alerts
          rules:
            - alert: HighErrorRate
              expr: increase(http_server_requests_seconds_count{status=~"4..|5.."}[30s]) > 10
              for: 0s
              labels:
                severity: warning
                environment: staging
                service: "{{ $labels.job }}"
              annotations:
                summary: "High error rate detected in staging"
                description: "Service {{ $labels.job }} has more than 10 error requests in the last 30 seconds. Current count: {{ $value }}"
                trace_query: 'http_server_requests_seconds_count{job="{{ $labels.job }}", status=~"4..|5.."}'
                log_query: '{namespace="petclinic-staging", container="{{ $labels.job }}"} |~ "ERROR|WARN"'
            - alert: ServiceDown
              expr: up == 0
              for: 1m
              labels:
                severity: warning
                environment: staging
              annotations:
                summary: "Service is down in staging"
                description: "Service {{ $labels.job }} has been down for more than 1 minute"
            - alert: HighResponseTime
              expr: histogram_quantile(0.95, rate(http_server_requests_seconds_bucket[5m])) > 1.5
              for: 2m
              labels:
                severity: warning
                environment: staging
              annotations:
                summary: "High response time in staging"
                description: "95th percentile response time for {{ $labels.job }} is above 1.5 seconds"
  alertmanagerFiles:
    alertmanager.yml:
      global:
        smtp_smarthost: 'localhost:587'
        smtp_from: 'staging-alerts@petclinic.com'
      route:
        group_by: ['alertname', 'environment']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        receiver: 'staging-notifications'
      receivers:
        - name: 'staging-notifications'
          webhook_configs:
            - url: 'http://staging-alertmanager-webhook:5001/'

loki-stack:
  grafana:
    enabled: true
    service:
      type: LoadBalancer
    adminPassword: staging123
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://petclinic-staging-prometheus-server.petclinic-staging.svc.cluster.local
            access: proxy
            isDefault: true
          - name: Loki
            type: loki
            url: http://petclinic-staging-loki.petclinic-staging.svc.cluster.local:3100
            access: proxy
            jsonData:
              derivedFields:
                - name: "Trace ID"
                  matcherRegex: "trace_id=(\\w+)"
                  url: "/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Btrace_id%3D%5C%22$${__value.raw}%5C%22%7D%22%7D%5D"
                - name: "Request ID"
                  matcherRegex: "request_id=(\\w+)"
                  url: "/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Brequest_id%3D%5C%22$${__value.raw}%5C%22%7D%22%7D%5D"
          - name: Jaeger
            type: jaeger
            url: http://tracing-server.petclinic-staging.svc.cluster.local:9411
            access: proxy
  loki:
    config:
      schema_config:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: staging_index_
              period: 24h
      server:
        http_listen_port: 3100
  promtail:
    enabled: true
    config:
      clients:
        - url: http://petclinic-staging-loki.petclinic-staging.svc.cluster.local:3100/loki/api/v1/push
      scrape_configs:
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod
              namespaces:
                names: ['petclinic-staging']
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_pod_container_name]
              target_label: container
            - source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_name]
              target_label: pod
            - source_labels: [__meta_kubernetes_pod_label_app]
              target_label: service
          pipeline_stages:
            - match:
                selector: '{container=~".*petclinic.*"}'
                stages:
                  - regex:
                      expression: '.*(?:traceId|trace.id|X-Trace-Id)[:=]\s*(?P<trace_id>[a-f0-9]+).*'
                  - regex:
                      expression: '.*(?:spanId|span.id|X-Span-Id)[:=]\s*(?P<span_id>[a-f0-9]+).*'
                  - regex:
                      expression: '.*(?:requestId|request.id|X-Request-Id)[:=]\s*(?P<request_id>[a-zA-Z0-9\-]+).*'
                  - regex:
                      expression: '.*\s(?P<level>ERROR|WARN|INFO|DEBUG|TRACE)\s.*'
                  - regex:
                      expression: '.*status[:=]\s*(?P<status_code>[0-9]+).*'
                  - labels:
                      trace_id:
                      span_id:
                      request_id:
                      level:
                      status_code:
                      environment: staging
