apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default # Hoặc project ArgoCD dành cho PROD
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "57.0.0" # Đảm bảo phiên bản nhất quán giữa các môi trường nếu có thể
    helm:
      # Sử dụng file values từ Git repo của bạn
      valueFiles:
        - https://raw.githubusercontent.com/hao-assignments/devops-lab03-monitoring/refs/heads/main/environments/prod/monitoring-values.yaml
  destination:
    server: https://kubernetes.default.svc # Cluster PROD (nếu có nhiều cluster)
    namespace: monitoring-prod # Namespace cho monitoring trên PROD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true