apiVersion: v2
name: petclinic
description: A Helm chart for Spring Petclinic microservices with monitoring
type: application
version: 0.1.0
appVersion: "2.7.0"

dependencies:
  - name: prometheus
    version: 27.20.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 9.2.2
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: loki-stack
    version: 2.9.3
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled