apiVersion: v2
name: petclinic
description: Spring PetClinic Microservices with Monitoring
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: "19.7.2"
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: "7.0.11"
  - name: loki
    repository: https://grafana.github.io/helm-charts
    version: "5.8.9"
  - name: promtail
    repository: https://grafana.github.io/helm-charts
    version: "6.15.3"