# Namespace will be provided by environment-specific values
namespace: "petclinic-template"

# Define all services in a single structure
services:
  config-server:
    enabled: true
    image: springcommunity/spring-petclinic-config-server:latest
    containerPort: 8888
    port: 8888
    serviceType: ClusterIP
    resources:
      limits:
        memory: 512Mi

  discovery-server:
    enabled: true
    image: springcommunity/spring-petclinic-discovery-server:latest
    containerPort: 8761
    port: 8761
    serviceType: ClusterIP
    useEureka: true
    resources:
      limits:
        memory: 512Mi

  customers-service:
    enabled: true
    image: springcommunity/spring-petclinic-customers-service:latest
    containerPort: 8081
    port: 8081
    serviceType: ClusterIP
    useEureka: true
    resources:
      limits:
        memory: 512Mi

  visits-service:
    enabled: true
    image: springcommunity/spring-petclinic-visits-service:latest
    containerPort: 8082
    port: 8082
    serviceType: ClusterIP
    useEureka: true
    resources:
      limits:
        memory: 512Mi

  vets-service:
    enabled: true
    image: springcommunity/spring-petclinic-vets-service:latest
    containerPort: 8083
    port: 8083
    serviceType: ClusterIP
    useEureka: true
    resources:
      limits:
        memory: 512Mi

  api-gateway:
    enabled: true
    image: springcommunity/spring-petclinic-api-gateway:latest
    containerPort: 8080
    port: 8080
    serviceType: ClusterIP
    resources:
      limits:
        memory: 512Mi

  admin-server:
    enabled: true
    image: springcommunity/spring-petclinic-admin-server:latest
    containerPort: 9090
    port: 9090
    serviceType: ClusterIP
    resources:
      limits:
        memory: 512Mi

  tracing-server:
    enabled: true
    image: openzipkin/zipkin:latest
    containerPort: 9411
    port: 9411
    serviceType: ClusterIP
    resources:
      limits:
        memory: 512Mi

# Monitoring configuration
prometheus:
  enabled: true
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  server:
    persistentVolume:
      enabled: false

loki-stack:
  promtail:
    enabled: true
    config:
      snippets:
        extraRelabelConfigs:
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - action: replace
            source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
      clients:
        - url: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push
  loki:
    persistence:
      enabled: true
      size: 5Gi
  grafana:
    enabled: true
    adminPassword: admin
    service:
      type: LoadBalancer
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://{{ .Release.Name }}-prometheus-server
            access: proxy
            isDefault: true
          - name: Loki
            type: loki
            url: http://{{ .Release.Name }}-loki:3100
            access: proxy
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        petclinic-dashboard:
          gnetId: 6756
          revision: 3
          datasource: Prometheus