# Namespace will be provided by environment-specific values
namespace: "petclinic-template"

# Define all services in a single structure
services:
  config-server:
    enabled: true
    image: springcommunity/spring-petclinic-config-server:latest
    containerPort: 8888
    port: 8888
    serviceType: ClusterIP
    resources:
      limits:
        memory: 512Mi

  discovery-server:
    enabled: true
    image: springcommunity/spring-petclinic-discovery-server:latest
    containerPort: 8761
    port: 8761
    serviceType: ClusterIP
    useEureka: true
    resources:
      limits:
        memory: 512Mi

  customers-service:
    enabled: true
    image: springcommunity/spring-petclinic-customers-service:latest
    containerPort: 8081
    port: 8081
    serviceType: ClusterIP
    useEureka: true
    resources:
      limits:
        memory: 512Mi

  visits-service:
    enabled: true
    image: springcommunity/spring-petclinic-visits-service:latest
    containerPort: 8082
    port: 8082
    serviceType: ClusterIP
    useEureka: true
    resources:
      limits:
        memory: 512Mi

  vets-service:
    enabled: true
    image: springcommunity/spring-petclinic-vets-service:latest
    containerPort: 8083
    port: 8083
    serviceType: ClusterIP
    useEureka: true
    resources:
      limits:
        memory: 512Mi

  api-gateway:
    enabled: true
    image: springcommunity/spring-petclinic-api-gateway:latest
    containerPort: 8080
    port: 8080
    serviceType: ClusterIP
    resources:
      limits:
        memory: 512Mi

  admin-server:
    enabled: true
    image: springcommunity/spring-petclinic-admin-server:latest
    containerPort: 9090
    port: 9090
    serviceType: ClusterIP
    resources:
      limits:
        memory: 512Mi

  tracing-server:
    enabled: true
    image: openzipkin/zipkin:latest
    containerPort: 9411
    port: 9411
    serviceType: ClusterIP
    resources:
      limits:
        memory: 512Mi

# Monitoring configuration
prometheus:
  enabled: true
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  server:
    persistentVolume:
      enabled: false
    service:
      type: ClusterIP
  serverFiles:
    prometheus.yml:
      global:
        scrape_interval: 15s
        evaluation_interval: 15s
      scrape_configs:
        - job_name: prometheus
          static_configs:
            - targets: ['localhost:9090']

loki-stack:
  promtail:
    enabled: true
    config:
      clients:
        - url: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push
      scrape_configs:
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod
              namespaces:
                names: ['{{ .Values.namespace }}']
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_pod_container_name]
              target_label: container
            - source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_name]
              target_label: pod
          pipeline_stages:
            - match:
                selector: '{container=~".*petclinic.*"}'
                stages:
                  - regex:
                      expression: '.*traceId=(?P<trace_id>[a-f0-9]+).*'
                  - labels:
                      trace_id:
  loki:
    persistence:
      enabled: true
      size: 5Gi
    config:
      schema_config:
        configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: "{{ .Values.namespace }}_index_"
              period: 24h
      server:
        http_listen_port: 3100
  grafana:
    enabled: true
    adminPassword: admin
    service:
      type: ClusterIP
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://{{ .Release.Name }}-prometheus-server
            access: proxy
            isDefault: true
          - name: Loki
            type: loki
            url: http://{{ .Release.Name }}-loki:3100
            access: proxy
          - name: Jaeger
            type: jaeger
            url: http://tracing-server.{{ .Values.namespace }}.svc.cluster.local:9411
            access: proxy
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'petclinic'
            orgId: 1
            folder: 'PetClinic'
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/petclinic
    dashboards:
      petclinic:
        service-overview:
          json: |
            {
              "dashboard": {
                "title": "PetClinic Services Overview",
                "panels": [
                  {
                    "title": "Request Rate",
                    "type": "graph",
                    "targets": [
                      {
                        "expr": "rate(http_server_requests_seconds_count[5m])",
                        "legendFormat": "{{ "{{" }} job {{ "}}" }} - {{ "{{" }} status {{ "}}" }}"
                      }
                    ]
                  },
                  {
                    "title": "Error Rate",
                    "type": "stat",
                    "targets": [
                      {
                        "expr": "rate(http_server_requests_seconds_count{status=~\"4..|5..\"}[5m])",
                        "legendFormat": "Errors/sec"
                      }
                    ]
                  },
                  {
                    "title": "Response Time",
                    "type": "graph",
                    "targets": [
                      {
                        "expr": "histogram_quantile(0.95, rate(http_server_requests_seconds_bucket[5m]))",
                        "legendFormat": "95th percentile"
                      }
                    ]
                  }
                ]
              }
            }