apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: {{ .Values.namespace }}
  labels:
    app: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
        - name: admin-server
          image: {{ .Values.admin_server.image }}
          ports:
            - containerPort: 9090
          resources:
            {{- toYaml .Values.admin_server.resources | nindent 12 }}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPRING_CLOUD_DISCOVERY_CLIENT_HEALTHINDICATOR_MANAGEMENT_PORT
              value: "${management.server.port:${server.port}}"
            - name: SPRING_CLOUD_DISCOVERY_CLIENT_HEALTHINDICATOR_MANAGEMENT_BASE_URL
              value: "http://${status.podIP}:${management.server.port:${server.port}}/actuator"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: {{ .Values.namespace }}
  labels:
    app: admin-server
spec:
  selector:
    app: admin-server
  ports:
    - protocol: TCP
      port: {{ .Values.admin_server.service.port }}
      targetPort: 9090
  type: {{ .Values.admin_server.service.type }}