apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: {{ .Values.namespace }}
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: {{ .Values.config_server.image }}
          ports:
            - containerPort: 8888
          resources:
            {{- toYaml .Values.config_server.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: {{ .Values.namespace }}
  labels:
    app: config-server
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: {{ .Values.config_server.service.port }}
      targetPort: 8888
  type: {{ .Values.config_server.service.type }}