# charts/petclinic/templates/customers-service-monitor.yaml
{{- if .Values.monitoring.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "petclinic.fullname" . }}-customers-service
  namespace: {{ .Release.Namespace }} # Namespace của PetClinic
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
    release: prometheus-stack # Label để Prometheus nhận diện (phải khớp với prometheusSpec.serviceMonitorSelector nếu có)
spec:
  selector:
    matchLabels:
      app: customers-service # Label của Pod mà Service này đại diện
  endpoints:
  - port: http # Tên port của service (phải khớp với tên port trong Service object)
    path: /actuator/prometheus
    interval: 15s
{{- end }}