apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: {{ .Values.namespace }}
  labels:
    app: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: {{ .Values.discovery_server.image }}
          ports:
            - containerPort: 8761
          resources:
            limits:
              memory: 512Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP # Use Pod IP as hostname
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: {{ .Values.namespace }}
  labels:
    app: discovery-server
spec:
  selector:
    app: discovery-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761