apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-server
  namespace: {{ .Values.namespace }}
  labels:
    app: tracing-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-server
  template:
    metadata:
      labels:
        app: tracing-server
    spec:
      containers:
        - name: tracing-server
          image: {{ .Values.tracing_server.image }}
          ports:
            - containerPort: 9411
          resources:
            {{- toYaml .Values.tracing_server.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tracing-server
  namespace: {{ .Values.namespace }}
  labels:
    app: tracing-server
spec:
  selector:
    app: tracing-server
  ports:
    - protocol: TCP
      port: {{ .Values.tracing_server.service.port }}
      targetPort: 9411
  type: {{ .Values.tracing_server.service.type }}