apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-server
  namespace: {{ .Values.namespace }}
  labels:
    app: tracing-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-server
  template:
    metadata:
      labels:
        app: tracing-server
    spec:
      containers:
        - name: tracing-server
          image: {{ .Values.tracing_server.image }}
          ports:
            - containerPort: 9411
          resources:
            limits:
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9411
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tracing-server
  namespace: {{ .Values.namespace }}
  labels:
    app: tracing-server
spec:
  selector:
    app: tracing-server
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
      {{- if .Values.tracing_server.nodePort }}
      nodePort: {{ .Values.tracing_server.nodePort }}
      {{- end }}
  # type: {{ .Values.tracing_server.serviceType | default "LoadBalancer" }}
  type: LoadBalancer