apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  namespace: {{ .Values.namespace }}
  labels:
    app: vets-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
        - name: vets-service
          image: {{ .Values.vets_service.image }}
          ports:
            - containerPort: 8083
          resources:
            limits:
              memory: 512Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8888
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://discovery-server:8761/eureka
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP # Use Pod IP as hostname
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"
            - name: SPRING_CLOUD_DISCOVERY_HEALTH_TIMEOUT
              value: "5000"
            - name: SPRING_CLOUD_DISCOVERY_CLIENT_HEALTHINDICATOR_USE-DISCOVERY-METADATA
              value: "true"
            - name: SPRING_CLOUD_DISCOVERY_CLIENT_HEALTHINDICATOR_MANAGEMENT_PORT
              value: "${management.server.port:${server.port}}"
            - name: SPRING_CLOUD_DISCOVERY_HEALTH_RETRY_MAX_ATTEMPTS
              value: "5"
            - name: SPRING_CLOUD_DISCOVERY_HEALTH_RETRY_INITIAL_INTERVAL
              value: "1000"
            - name: SPRING_CLOUD_DISCOVERY_CLIENT_HEALTHINDICATOR_MANAGEMENT_BASE_URL
              value: "http://${status.podIP}:${management.server.port:${server.port}}/actuator"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
  namespace: {{ .Values.namespace }}
  labels:
    app: vets-service
spec:
  selector:
    app: vets-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083