apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
  namespace: {{ .Values.namespace }}
  labels:
    app: visits-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
        - name: visits-service
          image: {{ .Values.visits_service.image }}
          ports:
            - containerPort: 8082
          resources:
            {{- toYaml .Values.visits_service.resources | nindent 12 }}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
  namespace: {{ .Values.namespace }}
  labels:
    app: visits-service
spec:
  selector:
    app: visits-service
  ports:
    - protocol: TCP
      port: {{ .Values.visits_service.service.port }}
      targetPort: 8082
  type: {{ .Values.visits_service.service.type }}