namespace: petclinic-prod

# Microservices configuration
config_server:
  image: springcommunity/spring-petclinic-config-server:latest

discovery_server:
  image: springcommunity/spring-petclinic-discovery-server:latest

customers_service:
  image: springcommunity/spring-petclinic-customers-service:latest

visits_service:
  image: springcommunity/spring-petclinic-visits-service:latest

vets_service:
  image: springcommunity/spring-petclinic-vets-service:latest

api_gateway:
  image: springcommunity/spring-petclinic-api-gateway:latest
  # service:
  #   type: LoadBalancer

tracing_server:
  image: openzipkin/zipkin:latest
  # service:
  #   type: LoadBalancer

admin_server:
  image: springcommunity/spring-petclinic-admin-server:latest
  # service:
  #   type: LoadBalancer

# Monitoring configuration
prometheus:
  enabled: true
  server:
    service:
      type: LoadBalancer

grafana:
  enabled: true
  service:
    type: LoadBalancer

loki:
  enabled: true
  service:
    name: loki-stack # Add this to ensure correct service name
  config:
    clients:
      - url: http://loki-stack.petclinic-prod.svc.cluster.local:3100/loki/api/v1/push
  