namespace: petclinic-prod

# Microservices configuration
config_server:
  image: springcommunity/spring-petclinic-config-server:latest

discovery_server:
  image: springcommunity/spring-petclinic-discovery-server:latest

customers_service:
  image: springcommunity/spring-petclinic-customers-service:latest

visits_service:
  image: springcommunity/spring-petclinic-visits-service:latest

vets_service:
  image: springcommunity/spring-petclinic-vets-service:latest

api_gateway:
  image: springcommunity/spring-petclinic-api-gateway:latest
  # service:
  #   type: LoadBalancer

tracing_server:
  image: openzipkin/zipkin:latest
  # service:
  #   type: LoadBalancer

admin_server:
  image: springcommunity/spring-petclinic-admin-server:latest
  # service:
  #   type: LoadBalancer

# Monitoring configuration
prometheus:
  enabled: true
  server:
    service:
      type: LoadBalancer
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: prometheus
          static_configs:
            - targets: ['localhost:9090']
        - job_name: api-gateway
          metrics_path: /actuator/prometheus
          static_configs:
            - targets: ['api-gateway.petclinic-prod.svc.cluster.local:8080']
        - job_name: customers-service
          metrics_path: /actuator/prometheus
          static_configs:
            - targets: ['customers-service.petclinic-prod.svc.cluster.local:8081']
        - job_name: visits-service
          metrics_path: /actuator/prometheus
          static_configs:
            - targets: ['visits-service.petclinic-prod.svc.cluster.local:8082']
        - job_name: vets-service
          metrics_path: /actuator/prometheus
          static_configs:
            - targets: ['vets-service.petclinic-prod.svc.cluster.local:8083']

loki-stack:
  grafana:
    enabled: true
    service:
      type: LoadBalancer