{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: petclinic
  labels:
    release: {{ .Values.prometheusReleaseLabel }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.podMonitor.appName }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - path: /actuator/prometheus
      port: http
      interval: 15s
{{- end }}