{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: petclinic-alerts
  labels:
    release: {{ .Values.prometheusReleaseLabel }}
spec:
  groups:
    - name: petclinic.rules
      rules:
        - alert: HighHttpLatency
          expr: histogram_quantile(0.95, rate(http_server_requests_seconds_bucket[5m])) > 1
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High HTTP latency (p95 > 1s)"
            description: "Service {{`{{ $labels.job }}`}} is experiencing high latency."
{{- end }}