apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: petclinic-alerts
  namespace: petclinic-prod
  labels:
    app: petclinic
spec:
  groups:
    - name: petclinic-alerts
      rules:
        - alert: High5xxRate
          expr: increase(http_server_requests_seconds_count{status=~"5.."}[30s]) > 10
          for: 0s
          labels:
            severity: warning
          annotations:
            summary: "High 5xx error rate"
            description: "More than 10 5xx requests in the last 30 seconds"
