apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-rules
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hao-assignments/devops-lab03-monitoring.git
    targetRevision: HEAD
    path: manifests/prometheus-rules
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
