apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hao-assignments/devops-lab02-kubernetes.git
    targetRevision: HEAD
    path: charts/petclinic
    helm:
      valueFiles:
        - ../../environments/staging/values.yaml
      parameters:
        - name: namespace
          value: petclinic-staging
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
