namespace: petclinic-dev

# Microservices configuration
config_server:
  image: springcommunity/spring-petclinic-config-server:latest

discovery_server:
  image: springcommunity/spring-petclinic-discovery-server:latest

customers_service:
  image: springcommunity/spring-petclinic-customers-service:latest

visits_service:
  image: springcommunity/spring-petclinic-visits-service:latest

vets_service:
  image: springcommunity/spring-petclinic-vets-service:latest

api_gateway:
  image: springcommunity/spring-petclinic-api-gateway:latest

admin_server:
  image: springcommunity/spring-petclinic-admin-server:latest

tracing_server:
  image: openzipkin/zipkin:latest

# Monitoring configuration
prometheus:
  enabled: true
  server:
    service:
      type: LoadBalancer

loki-stack:
  promtail:
    enabled: true
  loki:
    persistence:
      enabled: true
      size: 1Gi
  grafana:
    enabled: true
    service:
      type: LoadBalancer
